### ISSUE TITLE
Meet a problem when running RSIRL.m

### ISSUE THREAD

**Issue by BIT-LQX** [StanfordASL/RSIRL#1]
Hello, sir. I really appreciate your contributions about IRL and tried to run the code on the MATLAB 2016b. But the MATLAB reports the error that "the variable P_proj or the class P_proj.contains is not defined" in line 100 RSIRL.m. Could you give me a hand? Thanks a lot!

**Comment by ssingh19** [comment]
Make sure you have installed MPT 3.0 toolbox first. Otherwise, P_proj (a polyhedron object in the MPT toolbox) will not be defined.
